---
name: Upload Nightly Wheel

on:
  push:
    branches:
      - "master"

jobs:
  build-wheel:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Build wheel
        run: | 
          ./build_wheel.sh
          echo "::set-output name=wheel_path::$(ls dist/*.whl)"
          echo "::set-output name=wheel_name::$(basename $(ls dist/*.whl))"
        id: build_wheel
      - name: Upload Wheel Asset
        id: upload-release-asset 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build_wheel.outputs.wheel_path }}
          asset_name: ${{ steps.build_wheel.outputs.wheel_name }}
          tag: "nightly"
          overwrite: true
